version: '3.2'
services:
  #APP
  app:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${APP_PORT}:3000
    working_dir: /var/www/html
    volumes: 
      - .:/var/www/html:z
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    networks:
      - app-network
  #DATABASE
  database:
    image: mongo
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      AUTH: 'no'
    networks:
      - app-network
    volumes:
      - dbdata:/data/db
networks:
  app-network:
    driver: bridge
volumes: 
  dbdata: {}